name: Veeru_TestBuildConf

on: [workflow_dispatch]
env:
  PYTHON_ALLOW_CACHE: true
  PYTHON_DIR_CACHE: D:\.cache\python

jobs:
  Veeru_TestBuildConf:

    runs-on: windows-latest
    steps:
#    - name: Checkout repo
#      uses: actions/checkout@v4
#      with:
#        submodules: true

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: List files
      working-directory: .
      run: |
#           Get-ChildItem -Recurse -Path .git/modules *>&1
           Get-ChildItem -Recurse *>&1
#           Get-Content .git/config
           cmd /c set
